# Generated by Django 5.1 on 2024-11-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Meat', 'Meat'), ('SeaFood', 'SeaFood'), ('Grains', 'Grains'), ('Potatoes', 'Potatoes'), ('Fruits&Vegitables', 'Fruits & Vegetables'), ('Spices', 'Spices'), ('Beverages', 'Beverages'), ('BakingEssentials', 'Baking Essentials')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('measurement', models.CharField(max_length=100)),
            ],
        ),
    ]
