# Generated by Django 5.1 on 2024-11-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Meat', 'Meat'), ('SeaFood', 'SeaFood'), ('Grains', 'Grains'), ('Potatoes', 'Potatoes'), ('Fruits&Vegitables', 'Fruits & Vegetables'), ('Spices', 'Spices'), ('Beverages', 'Beverages'), ('BakingEssentials', 'Baking Essentials')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
